// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AccountProvider string

const (
	AccountProviderGITHUB AccountProvider = "GITHUB"
)

func (e *AccountProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountProvider(s)
	case string:
		*e = AccountProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountProvider: %T", src)
	}
	return nil
}

type NullAccountProvider struct {
	AccountProvider AccountProvider `json:"AccountProvider"`
	Valid           bool            `json:"valid"` // Valid is true if AccountProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AccountProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountProvider), nil
}

type Role string

const (
	RoleADMIN   Role = "ADMIN"
	RoleMEMBER  Role = "MEMBER"
	RoleBILLING Role = "BILLING"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"Role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type TokenType string

const (
	TokenTypePASSWORDRECOVER TokenType = "PASSWORD_RECOVER"
)

func (e *TokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenType(s)
	case string:
		*e = TokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenType: %T", src)
	}
	return nil
}

type NullTokenType struct {
	TokenType TokenType `json:"TokenType"`
	Valid     bool      `json:"valid"` // Valid is true if TokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.TokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenType), nil
}

type Account struct {
	ID                string          `json:"id"`
	Provider          AccountProvider `json:"provider"`
	ProviderAccountID string          `json:"provider_account_id"`
	UserID            string          `json:"user_id"`
}

type Invite struct {
	ID             string         `json:"id"`
	Email          string         `json:"email"`
	Role           Role           `json:"role"`
	CreatedAt      time.Time      `json:"created_at"`
	AuthorID       sql.NullString `json:"author_id"`
	OrganizationID string         `json:"organization_id"`
}

type Member struct {
	ID             string `json:"id"`
	Role           Role   `json:"role"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

type Organization struct {
	ID                        string         `json:"id"`
	Name                      string         `json:"name"`
	Slug                      string         `json:"slug"`
	Domain                    sql.NullString `json:"domain"`
	ShouldAttachUsersByDomain bool           `json:"should_attach_users_by_domain"`
	AvatarUrl                 sql.NullString `json:"avatar_url"`
	CreatedAt                 time.Time      `json:"created_at"`
	UpdatedAt                 time.Time      `json:"updated_at"`
	OwnerID                   string         `json:"owner_id"`
}

type Project struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Slug           string         `json:"slug"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	OrganizationID string         `json:"organization_id"`
	OwnerID        string         `json:"owner_id"`
}

type Token struct {
	ID        string    `json:"id"`
	Type      TokenType `json:"type"`
	CreatedAt time.Time `json:"created_at"`
	UserID    string    `json:"user_id"`
}

type User struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
