// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id string) (GetUserRow, error)
}

var _ Querier = (*Queries)(nil)
